### ISSUE TITLE
阿里云OSS储存策略参数设置正确但图片上传失败

### ISSUE THREAD

**Issue by Deemai** [lsky-org/lsky-pro#595]
<h2>储存策略为阿里云OSS时上传失败</h2>
<p>参数正确填写，但上传图片失败</p>
<p>log日志保存如下</p>
<br>
<h3>1.Bucket 名称填写完整包含域名</h3>
`[2023-01-16 16:20:21] prod.ERROR: 保存图片时出现异常 {"file":"/www/wwwroot/img.nai*****dio.cn/vendor/league/flysystem/src/UnableToWriteFile.php","line":24,"message":"Unable to write file at location: 2023/01/16/63c508c5c1ea5.jpg. \"cd*****tu.oss-cn-shenzhen.aliyuncs.com\"bucket name is invalid","trace":"#0 /www/wwwroot/img.nai*****dio.cn/vendor/zing/flysystem-oss/src/OssAdapter.php(195): League\\Flysystem\\UnableToWriteFile::atLocation('2023/01/16/63c5...', '\"cd*****tu.oss-...', Object(OSS\\Core\\OssException))`
<br>
<h3>2.单填写 Bucket 名称</h3>
`[2023-01-16 16:55:42] prod.ERROR: Web 上传文件时发生异常 {"file":"/www/wwwroot/img.nai*****dio.cn/vendor/aliyuncs/oss-sdk-php/src/OSS/OssClient.php","line":3267,"message":"Call to undefined function OSS\\iconv()","trace":"#0 /www/wwwroot/img.nai*****dio.cn/vendor/aliyuncs/oss-sdk-php/src/OSS/OssClient.php(3008): OSS\\OssClient->authPrecheckObjectEncoding(Array)`
<br>
<p>参数填写如图所示</p>
![屏幕截图 2023-01-16 170015](https://user-images.githubusercontent.com/51120688/212638611-83c8957d-c94e-4426-87bf-2df4d6b62699.jpg)

**Comment by jijidom** [comment]
我也是碰到了同样的问题，报错也一模一样，我敢肯定我配置没有写错，但就是上传失败

**Comment by akatsukiro** [comment]
我刚刚测试了一下。没有问题。
![image](https://github.com/lsky-org/lsky-pro/assets/69096852/79501f8a-0eb3-4435-986d-4e2bd26232bc)
