### ISSUE TITLE
似乎 AWS S3 的配置项与 Cloudflare R2 不兼容

### ISSUE THREAD

**Issue by Big-Cake-jpg** [lsky-org/lsky-pro#600]
如题。

### 问题描述

Cloudflare R2 的 S3 API 格式是 `https://<ACCOUNT-ID>.r2.cloudflarestorage.com/<BUCKET-ID>`，但是兰空图床在拼接链接格式时会将本应该放在 API 末尾 `<BUCKET-ID>` 处的桶名放在本应该放账户 ID 的开头 `<ACCOUNT-ID>` 处，且直接将用户组中设置的链接格式拼接至末尾 `<BUCKET-ID>` 处，导致上传图片出错。

查看日志，显示服务器返回了 404 错误，描述为“找不到对应的存储桶”。如果手动修改用户组链接格式，则会导致生成的图片直链中带有桶名导致无法加载。

对于图片直链的问题，我目前的方案是添加一个页面规则来缓解。

### 预期行为

能够正确拼接 API 地址并生成图片直链

### 错误日志
```
[2023-01-21 09:46:16] prod.ERROR: 保存图片时出现异常 {"file":"/www/wwwroot/img.bigcake.cakemc.top/vendor/league/flysystem/src/UnableToWriteFile.php","line":24,"message":"Unable to write file at location: 2023/01/21/63cb43e815745.webp. Error executing \"PutObject\" on \"https://1655b7b3abffdf84dba9bcf5882cf383.r2.cloudflarestorage.com/2023/01/21/63cb43e815745.webp\"; AWS HTTP error: Client error: `PUT https://1655b7b3abffdf84dba9bcf5882cf383.r2.cloudflarestorage.com/2023/01/21/63cb43e815745.webp` resulted in a `404 Not Found` response:
<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Mes (truncated...)
 NoSuchBucket (client): The specified bucket does not exist. - <?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist.</Message></Error>","trace":"#0 /www/wwwroot/img.bigcake.cakemc.top/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(208): League\\Flysystem\\UnableToWriteFile::atLocation()
#1 /www/wwwroot/img.bigcake.cakemc.top/vendor/league/flysystem-aws-s3-v3/AwsS3V3Adapter.php(249): League\\Flysystem\\AwsS3V3\\AwsS3V3Adapter->upload()
#2 /www/wwwroot/img.bigcake.cakemc.top/vendor/league/flysystem/src/Filesystem.php(68): League\\Flysystem\\AwsS3V3\\AwsS3V3Adapter->writeStream()
#3 /www/wwwroot/img.bigcake.cakemc.top/app/Services/ImageService.php(214): League\\Flysystem\\Filesystem->writeStream()
#4 /www/wwwroot/img.bigcake.cakemc.top/app/Http/Controllers/Controller.php(129): App\\Services\\ImageService->store()
#5 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Controller->upload()
#6 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#7 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#8 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#9 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#10 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#11 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#13 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#15 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#17 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#19 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#20 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#22 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#24 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#26 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#27 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#28 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#29 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#30 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#31 /www/wwwroot/img.bigcake.cakemc.top/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#33 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#35 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#36 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#39 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#41 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#43 /www/wwwroot/img.bigcake.cakemc.top/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#45 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#47 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#49 /www/wwwroot/img.bigcake.cakemc.top/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#50 /www/wwwroot/img.bigcake.cakemc.top/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#51 {main}"} 
```
### 复现步骤

1. 在 Cloudflare 仪表盘处创建一个 R2 存储桶
2. 生成一个 R2 API 令牌
3. 如下图所示进行配置：
![image](https://user-images.githubusercontent.com/76810494/213837994-196abc23-05aa-4ace-8b9c-975d9884d6b4.png)
4. 尝试上传图片

### 系统环境

Ubuntu 22.04 LTS 
Nginx - Tengine 2.2.4 (2.3.3)
PHP 8.1.13
MySQL 8.0.24
- [x] 使用宝塔面板

**Comment by SkysCrystal** [comment]
你这里的连接地址没有写全吧

**Comment by zui-lang** [comment]
你的连接地址和存储桶名称填错了

**Comment by Big-Cake-jpg** [comment]
> 你的连接地址和存储桶名称填错了

了解，已解决。
