### ISSUE TITLE
初始化时报500错误

### ISSUE THREAD

**Issue by Redmomn** [lsky-org/lsky-pro#650]
刚刚安装好兰空，进网站就报500错误，php版本是8.2，扩展和函数都满足要求，数据库版本也足够
求大佬解答
这是storage/logs的日志文件
```
[2023-04-19 23:19:45] production.ERROR: Carbon\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /usr/local/nginx/lsky-pro/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98 {"exception":"[object] (TypeError(code: 0): Carbon\\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /usr/local/nginx/lsky-pro/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php on line 98 at /usr/local/nginx/lsky-pro/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php:928)
[stacktrace]
#0 /usr/local/nginx/lsky-pro/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(98): Carbon\\Carbon::setLastErrors()
#1 /usr/local/nginx/lsky-pro/vendor/nesbot/carbon/src/Carbon/Traits/Creator.php(252): Carbon\\Carbon->__construct()
#2 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(259): Carbon\\Carbon::now()
#3 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(221): Illuminate\\Session\\Middleware\\StartSession->getCookieExpirationDate()
#4 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(125): Illuminate\\Session\\Middleware\\StartSession->addCookieToResponse()
#5 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#6 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#7 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#9 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#11 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(724): Illuminate\\Pipeline\\Pipeline->then()
#13 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#14 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#15 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#16 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#17 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#18 /usr/local/nginx/lsky-pro/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(59): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#20 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#22 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#23 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#25 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#26 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#28 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#30 /usr/local/nginx/lsky-pro/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#32 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#34 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#36 /usr/local/nginx/lsky-pro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#37 /usr/local/nginx/lsky-pro/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#38 {main}
"} 
```

**Comment by Redmomn** [comment]
php8.2好像不行，换到8.0就好了

**Comment by zhimibuwudn** [comment]
php8.2解决办法：修改vendor/nesbot/carbon/src/Carbon/Traits/Creator.php的第928行
```
#private static function setLastErrors(array $lastErrors)
private static function setLastErrors($lastErrors)
```
原文：https://www.nginxisok.com/blog/lsky-500-internal-error.html
